% A robot enters an error state after detecting a fault, R4.1

forall n:Nat,e:Error . val(n < 3) =>
[true*.fault(n,e)]Error_state(n)